longbinlai/GraphScope

research/gaia-x/ir/core/Cargo.toml, research/gaia-x/ir/core/src/plan/ffi.rs, research/gaia-x/ir/core/src/plan/logical.rs, research/gaia-x/ir/core/src/plan/mod.rs, research/gaia-x/ir/core/src/plan/physical.rs, research/gaia-x/ir/proto/algebra.proto, research/gaia-x/ir/proto/expr.proto, research/gaia-x/pegasus/clients/rust/client/src/builder.rs
Implement transforming merge/join kind of plan into a physical plan and testing the correctness.
=> Ir physical plan

research/gaia-x/ir/core/src/plan/ffi.rs, research/gaia-x/ir/core/src/plan/physical.rs
=> Use pb::logical_plan::Operator instead of each specific operator in physical plan

research/gaia-x/ir/core/src/plan/physical.rs
=> [WIP: ir_physical_plan] Support producing orderby in physical plan.

research/gaia-x/ir/runtime/src/expr/eval.rs
=> Permitting None tag in a Variable 

research/gaia-x/ir/core/src/plan/ffi.rs
=> Remove ResultCode from FfiJobBuffer to avoid a JNA conflict. 

research/gaia-x/ir/core/src/plan/ffi.rs
=> Check whether a pointer is null before destroying it. 

research/gaia-x/ir/compiler/Makefile, research/gaia-x/ir/compiler/conf/gremlin-server.yaml, research/gaia-x/ir/compiler/pom.xml, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/common/exception/SetPrivateFieldException.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/IrPlanBuidler.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/IrStandardOpProcessor.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/OpArgTransformFactory.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/Utils.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/service/GraphServiceMain.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/service/IrOpLoader.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/service/IrOpSelectorHandler.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/service/IrWsAndHttpChannelizer.java
1. add gremlin server
2. add copyright
Fixes
=> add gremlin server

research/gaia-x/ir/docker/Dockerfile
=> add Dockerfile to build ir based runtime image

research/gaia-x/ir/compiler/pom.xml
=> upgrade version of proto

research/gaia-x/ir/compiler/pom.xml, research/gaia-x/ir/compiler/src/main/antlr4/GremlinGS.g4, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/IrPlanBuidler.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/GenericLiteralVisitor.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/GraphTraversalSourceVisitor.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/GremlinAntlrToJava.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalMethodVisitor.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalPredicateVisitor.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalRootVisitor.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalSourceSpawnMethodVisitor.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/exception/StepUnsupportedException.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/exception/UnsupportedAntlrException.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/exception/UnsupportedEvalException.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/processor/IrOpLoader.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/processor/IrStandardOpProcessor.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/script/AntlrToJavaScriptEngine.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/script/AntlrToJavaScriptEngineFactory.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/service/GraphServiceMain.java, research/gaia-x/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/service/IrOpSelectorHandler.java, research/gaia-x/ir/compiler/src/main/resources/META-INF/services/org.apache.tinkerpop.gremlin.jsr223.GremlinScriptEngineFactory, research/gaia-x/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/EmptyTest.java, research/gaia-x/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/GraphStepTest.java, research/gaia-x/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/HasStepTest.java, research/gaia-x/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/LimitTest.java, research/gaia-x/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/VertexStepTest.java, research/gaia-x/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/AntlrEvalTest.java
=> add antlr parser in ir compiler

research/query_service/ir/compiler/src/main/antlr4/GremlinGS.g4, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/IrPlanBuidler.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/GremlinAntlrToJava.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/exception/InvalidGremlinScriptException.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/exception/UnsupportedEvalException.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/exception/UnsupportedStepException.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/script/AntlrToJavaScriptEngine.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/NegativeEvalTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/PositiveEvalTest.java
&& remove pattern [g] from supported list of gremlin query
1，add InvalidGremlinScriptException && NegativeEvalTest
2，remove pattern [g] from supported list of gremlin query
Fixes
=> add InvalidGremlinScriptException && NegativeEvalTest

research/query_service/ir/runtime/src/compiler.rs
=> Support dedup() and dedup().by()

research/query_service/ir/compiler/src/main/antlr4/GremlinGS.g4
=> update antlr to add support to group && dedup && within/without

research/engine/pegasus/clients/java/client/src/main/java/com/alibaba/pegasus/builder/Plan.java, research/query_service/gremlin/compiler/gremlin-server-plugin/src/main/java/com/alibaba/graphscope/gaia/plan/PlanUtils.java, research/query_service/gremlin/compiler/gremlin-test/src/main/java/com/alibaba/graphscope/gaia/GaiaGremlinTest.java
=> fix pegasus client compiling errors

research/query_service/ir/compiler/src/main/antlr4/GremlinGS.g4, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/OpArgTransformFactory.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalPredicateVisitor.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/HasStepTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/PositiveEvalTest.java
=> add predicates {lt, lte, gt, gte, within, without}

research/query_service/ir/common/Cargo.toml, research/query_service/ir/common/build.rs, research/query_service/ir/common/src/lib.rs
=> [Gaia/IR] Simplify the json_serde for ir pb

research/query_service/ir/common/src/lib.rs, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/IrPlan.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/jna/IrCoreLibrary.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/common/ScanFusionOpTest.java, research/query_service/ir/compiler/src/test/resources/scan_expr.json, research/query_service/ir/compiler/src/test/resources/scan_ids.json, research/query_service/ir/compiler/src/test/resources/scan_labels.json, research/query_service/ir/compiler/src/test/resources/scan_opt.json, research/query_service/ir/core/src/plan/ffi.rs, research/query_service/ir/core/src/plan/logical.rs, research/query_service/ir/core/src/plan/physical.rs, research/query_service/ir/integrated/tests/auxilia_test.rs, research/query_service/ir/integrated/tests/common/mod.rs, research/query_service/ir/integrated/tests/expand_test.rs, research/query_service/ir/integrated/tests/graph_query_test.rs, research/query_service/ir/integrated/tests/scan_test.rs, research/query_service/ir/proto/algebra.proto, research/query_service/ir/runtime/src/expr/eval.rs, research/query_service/ir/runtime/src/process/operator/source.rs
=> Ir index pred

research/query_service/ir/runtime/src/process/operator/filter/select.rs, research/query_service/ir/runtime/src/process/operator/join/join.rs, research/query_service/ir/runtime/src/process/operator/keyed/keyed.rs, research/query_service/ir/runtime/src/process/operator/map/project.rs, research/query_service/ir/runtime/src/process/operator/mod.rs, research/query_service/ir/runtime/src/process/operator/sink.rs, research/query_service/ir/runtime/src/process/operator/sort/sort.rs
=> More uts for project and order in IR runtime 

research/query_service/ir/compiler/src/main/antlr4/GremlinGS.g4, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalMethodVisitor.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/NegativeEvalTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/PositiveEvalTest.java
=> Fix grammar parser of as(..)

research/query_service/ir/compiler/src/main/antlr4/GremlinGS.g4, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/IrPlan.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/InterOpCollectionBuilder.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/OpArgTransformFactory.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/common/intermediate/operator/GroupOpTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/CountStepTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/ValueMapTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/PositiveEvalTest.java, research/query_service/ir/compiler/src/test/resources/count.json, research/query_service/ir/compiler/src/test/resources/count_as.json
=> add count and values in compiler

research/query_service/ir/runtime/src/compiler.rs, research/query_service/ir/runtime/src/process/functions.rs, research/query_service/ir/runtime/src/process/operator/accum/accum.rs, research/query_service/ir/runtime/src/process/operator/group/fold.rs, research/query_service/ir/runtime/src/process/operator/group/mod.rs
1. Support fold in Runtime with Accumulator
2. Support simple count as an optimization 
Fixes
=> Support fold in Runtime

research/query_service/ir/core/src/plan/logical.rs, research/query_service/ir/core/src/plan/physical.rs, research/query_service/ir/runtime/src/process/operator/group/group.rs, research/query_service/ir/runtime/src/process/operator/keyed/keyed.rs, research/query_service/ir/runtime/src/process/operator/sink.rs
fix bug when querying groupCount().by("name")
Fixes
=> Fix bug in adding group/dedup op in physical plan

research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/InterOpCollectionBuilder.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalMethodVisitor.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/SelectStepTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/PositiveEvalTest.java
1.  add SelectOneStep in gremlin to parse pattern [select("a")] or [select("a").by(..)], to fix bugs.
2. add transformations from SelectOneStep to ProjectOp.
3. update and add related tests.
Fixes
=> fix select one tag

research/query_service/ir/runtime/src/process/operator/sink.rs, research/query_service/ir/runtime/src/process/record.rs
=> [IR Runtime] sink head and all columns by default

research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/IrPlan.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/InterOpCollection.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/operator/OrderOp.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/operator/ProjectOp.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/strategy/InterOpStrategy.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/strategy/TopKStrategy.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/common/intermediate/operator/OrderOpTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/common/intermediate/strategy/TopKStrategyTest.java, research/query_service/ir/compiler/src/test/resources/order_asc.json, research/query_service/ir/compiler/src/test/resources/order_key.json, research/query_service/ir/compiler/src/test/resources/order_keys.json, research/query_service/ir/compiler/src/test/resources/order_label.json, research/query_service/ir/compiler/src/test/resources/order_limit.json
1. add TopKStrategy to fuse order with the limit.
2. add OrderOp  && TopKStrategy tests.
Fixes
=> apply top-k strategy

research/query_service/ir/runtime/src/process/operator/map/project.rs, research/query_service/ir/runtime/src/process/record.rs
=> [Bug fix] fix bug when project multi columns with is_append=true

research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/IrPlan.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/jna/IrCoreLibrary.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/processor/IrStandardOpProcessor.java
=> add workers and servers in build physical plan

research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/processor/IrStandardOpProcessor.java
=> set different job id for different query

research/query_service/ir/graph_proxy/src/exp_store/graph_query.rs, research/query_service/ir/runtime/src/graph/property.rs
=> [Bug fix] fix bug when shuffle lazy properties

research/query_service/ir/common/src/lib.rs
=> Bug fix: process Object::None in sinking

research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/jna/IrCoreLibrary.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/jna/type/FfiJobBuffer.java
release job buffer by value to fix bugs in ci test
Fixes
=> release job buffer by value

research/query_service/ir/compiler/src/main/antlr4/GremlinGS.g4, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/OpArgTransformFactory.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/AnyValue.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalMethodVisitor.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalPredicateVisitor.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/GraphStepTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/HasStepTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/PositiveEvalTest.java
1, update antlr and support more predicate pattens
2, check property existence before filtering by predicates
Fixes
=> fix predicates in has

research/query_service/ir/compiler/src/main/antlr4/GremlinGS.g4, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/OpArgTransformFactory.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalMethodVisitor.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/GraphStepTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/HasStepTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/integration/graph/RemoteTestGraph.java
=> revert updates to checking existence of property before predicate

research/query_service/ir/core/src/plan/logical.rs, research/query_service/ir/integrated/Cargo.toml, research/query_service/ir/integrated/tests/graph_query_test.rs, research/query_service/ir/runtime/src/process/operator/map/project.rs, research/query_service/ir/runtime/src/process/operator/mod.rs
=> Ir fix project

research/query_service/ir/common/src/lib.rs, research/query_service/ir/core/src/plan/logical.rs, research/query_service/ir/core/src/plan/physical.rs, research/query_service/ir/proto/algebra.proto
=> [Gaia/IR] Add Path Expand to Logical/Physical Plans.

research/query_service/ir/compiler/src/test/resources/expand_alias.json, research/query_service/ir/compiler/src/test/resources/expand_edge_opt.json, research/query_service/ir/compiler/src/test/resources/expand_labels.json
=> update expected results of expand with the changes of pb

research/query_service/ir/runtime/src/process/operator/mod.rs
=> Bug fix: fix bug in get_entry() for GraphObject

research/query_service/ir/proto/results.proto, research/query_service/ir/runtime/src/graph/element/path.rs, research/query_service/ir/runtime/src/process/operator/sink/sink.rs, research/query_service/ir/runtime/src/process/record.rs
=> [IR Runtime] Sink for GraphPath

research/query_service/ir/integrated/tests/apply_test.rs, research/query_service/ir/integrated/tests/common/mod.rs, research/query_service/ir/runtime/src/compiler.rs, research/query_service/ir/runtime/src/process/functions.rs, research/query_service/ir/runtime/src/process/operator/mod.rs, research/query_service/ir/runtime/src/process/operator/subtask/apply.rs, research/query_service/ir/runtime/src/process/operator/subtask/mod.rs
1.  Parse and install Apply in IRJobCompiler
2. Implement Apply UDF in Runtime UDFGen
3. Add UTs for Apply
Fixes
=> [IR Runtime] Support Apply in Runtime

research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/IrPlan.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/process/SinkArg.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/process/SinkOutputProcessor.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/jna/IrCoreLibrary.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/GremlinResultParserFactory.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/OpArgTransformFactory.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/SelectStepTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/ValueMapTest.java, research/query_service/ir/core/src/plan/ffi.rs, research/query_service/ir/integrated/tests/graph_query_test.rs, research/query_service/ir/proto/algebra.proto, research/query_service/ir/runtime/src/process/operator/sink/sink.rs
=> Ir refine sink

research/query_service/ir/compiler/src/main/antlr4/GremlinGS.g4, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalMethodVisitor.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/OpArgTransformFactory.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/NegativeEvalTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/PositiveEvalTest.java
1. support select('a').by()
2. support where(eq('a')).by()
3. support order().by()
4. support group().by().by()
Fixes
=> support by empty

research/query_service/ir/runtime/src/process/operator/sink/sink.rs
=> [IR Runtime] Do not sink column if corresponding entry is None

research/query_service/ir/runtime/src/process/operator/map/project.rs, research/query_service/ir/runtime/src/process/record.rs
=> [IR Runtime] set Head as None after project multiple columns

research/query_service/ir/integrated/tests/apply_test.rs, research/query_service/ir/integrated/tests/graph_query_test.rs, research/query_service/ir/integrated/tests/pathxd_test.rs
=> [Runtime UT] add shuffle op in integration uts and add test cases of worker_num = 2

research/query_service/ir/compiler/src/main/antlr4/GremlinGS.g4, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/IrPlan.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/InterOpCollection.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/operator/UnionOp.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/process/SinkArg.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/process/SinkOutputProcessor.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/jna/IrCoreLibrary.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/InterOpCollectionBuilder.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/NestedTraversalSourceListVisitor.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalMethodVisitor.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/processor/IrTestOpProcessor.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/processor/IrStandardOpProcessor.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/strategy/RemoveUselessStepStrategy.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/GremlinResultAnalyzer.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/GremlinResultParserFactory.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/OpArgTransformFactory.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/PositiveEvalTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/integration/graph/RemoteTestGraph.java, research/query_service/ir/core/src/plan/ffi.rs, research/query_service/ir/proto/algebra.proto
1. support union multiple sub_plans in compiler 
2. add union interface in ir core
Fixes
=> support union

research/query_service/ir/runtime/src/process/operator/accum/accum.rs, research/query_service/ir/runtime/src/process/operator/keyed/keyed.rs, research/query_service/ir/runtime/src/process/operator/map/project.rs, research/query_service/ir/runtime/src/process/operator/mod.rs, research/query_service/ir/runtime/src/process/operator/sort/sort.rs
=> [IR Runtime] update EntryAccumulator, and impl Encode/Decode for it

research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/InterOpCollectionBuilder.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/GremlinResultAnalyzer.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/GremlinResultParserFactory.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/ParserUtils.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/PathExpandStepTest.java
=> Fix path expand

research/query_service/ir/runtime/src/process/operator/accum/accum.rs
=> [IR Runtime] use Count<()> in EntryAccumulator

research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/ArgUtils.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/jna/IrCoreLibrary.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/jna/type/FfiPropertyOpt.java
=> fix variable of path expand length

research/query_service/ir/core/src/plan/logical.rs, research/query_service/ir/core/src/plan/meta.rs, research/query_service/ir/core/src/plan/physical.rs
=> Ir fix union

research/query_service/ir/core/src/plan/ffi.rs, research/query_service/ir/core/src/plan/logical.rs, research/query_service/ir/core/src/plan/meta.rs, research/query_service/ir/core/src/plan/physical.rs, research/query_service/ir/graph_proxy/src/exp_store/graph_query.rs, research/query_service/ir/integrated/tests/apply_test.rs, research/query_service/ir/integrated/tests/auxilia_test.rs, research/query_service/ir/integrated/tests/expand_test.rs, research/query_service/ir/integrated/tests/graph_query_test.rs, research/query_service/ir/integrated/tests/pathxd_test.rs, research/query_service/ir/integrated/tests/scan_test.rs, research/query_service/ir/proto/algebra.proto, research/query_service/ir/runtime/src/graph/mod.rs
=> [IR Runtime] support get_all props in QueryParam

research/query_service/ir/common/src/lib.rs, research/query_service/ir/core/src/error.rs, research/query_service/ir/core/src/plan/ffi.rs, research/query_service/ir/core/src/plan/logical.rs, research/query_service/ir/core/src/plan/physical.rs, research/query_service/ir/integrated/tests/apply_test.rs, research/query_service/ir/integrated/tests/auxilia_test.rs, research/query_service/ir/integrated/tests/common/mod.rs, research/query_service/ir/integrated/tests/expand_test.rs, research/query_service/ir/integrated/tests/graph_query_test.rs, research/query_service/ir/integrated/tests/pathxd_test.rs, research/query_service/ir/integrated/tests/scan_test.rs, research/query_service/ir/proto/algebra.proto, research/query_service/ir/runtime/src/graph/mod.rs, research/query_service/ir/runtime/src/process/operator/map/mod.rs
As titled. 
This PR includes adding QueryParams back to GetV operator and the corresponding pre/post processing logics.
=> Define Pattern Matching operator in IR

research/query_service/ir/compiler/Makefile, research/query_service/ir/compiler/conf/gremlin-server.yaml, research/query_service/ir/compiler/pom.xml, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/config/Configs.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/result/GremlinTestResultProcessor.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/integration/graph/RemoteTestGraph.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/integration/ldbc/IrLdbcTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/integration/ldbc/IrLdbcTestSuite.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/integration/ldbc/LdbcQueryTest.java
1. add ldbc tests.
2. set default gremlin timeout to 600s to pass the ldbc6.
Fixes
=> Add ldbc test

research/query_service/ir/runtime/src/process/operator/mod.rs, research/query_service/ir/runtime/src/process/operator/subtask/apply.rs
=> [Bug Fix] allow # of subtask results > 1 

research/query_service/ir/compiler/src/main/antlr4/GremlinGS.g4, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/ArgUtils.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/InterOpCollectionBuilder.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalMethodVisitor.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/GremlinResultAnalyzer.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/GremlinResultParserFactory.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/StepTransformFactory.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/TraversalParentTransformFactory.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/alias/AliasArg.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/alias/AliasManager.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/alias/AliasPrefixType.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/alias/GetAliasArg.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/CountStepTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/subtask/GroupStepTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/subtask/OrderStepTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/subtask/SelectStepTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/integration/ldbc/LdbcQueryTest.java
=> Refine alias

research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/processor/IrStandardOpProcessor.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/ExprArg.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/ExprRes.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/ExprResult.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/PredicateExprTransform.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/StepTransformFactory.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/TraversalParentTransform.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/TraversalParentTransformFactory.java
=> refine interface of judging whether a sub_traversal can be converted to expression

research/query_service/ir/compiler/src/main/antlr4/GremlinGS.g4, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/IrPlan.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/MatchSentence.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/operator/MatchOp.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/intermediate/process/SinkOutputProcessor.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/jna/IrCoreLibrary.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/common/jna/type/FfiBinderOpt.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/InterOpCollectionBuilder.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalMethodVisitor.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/strategy/RemoveUselessStepStrategy.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/result/GremlinResultAnalyzer.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/transform/StepTransformFactory.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/MatchStepTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/PositiveEvalTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/integration/IrGremlinTestSuite.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/integration/graph/RemoteTestGraph.java
=> Support match in compiler

research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/common/intermediate/operator/ProjectOpTest.java
=> Update tests according to changes with ir_core

research/query_service/ir/compiler/src/main/antlr4/GremlinGS.g4, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/antlr4/TraversalMethodVisitor.java, research/query_service/ir/compiler/src/main/java/com/alibaba/graphscope/gremlin/plugin/traversal/IrCustomizedTraversal.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/gremlin/antlr4/PositiveEvalTest.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/integration/graph/RemoteTestGraph.java, research/query_service/ir/compiler/src/test/java/com/alibaba/graphscope/integration/ldbc/LdbcQueryTest.java
=> Add enV() step

research/query_service/ir/common/src/lib.rs, research/query_service/ir/core/src/plan/ffi.rs, research/query_service/ir/core/src/plan/logical.rs, research/query_service/ir/core/src/plan/physical.rs, research/query_service/ir/proto/algebra.proto
1. Update proto of Union to include the case of Intersection
2. Translate Union of Intersection into physical op
3. Add CI for translation of union (intersection case)
Fixes
=> [IR Core] Support Union of Intersection in IR-Core

research/query_service/ir/integrated/tests/expand_test.rs, research/query_service/ir/runtime/Cargo.toml, research/query_service/ir/runtime/src/compiler.rs, research/query_service/ir/runtime/src/error.rs, research/query_service/ir/runtime/src/graph/element/mod.rs, research/query_service/ir/runtime/src/graph/element/path.rs, research/query_service/ir/runtime/src/process/operator/accum/accum.rs, research/query_service/ir/runtime/src/process/operator/flatmap/edge_expand.rs, research/query_service/ir/runtime/src/process/operator/flatmap/mod.rs, research/query_service/ir/runtime/src/process/operator/flatmap/unfold.rs, research/query_service/ir/runtime/src/process/operator/group/group.rs, research/query_service/ir/runtime/src/process/operator/map/auxilia.rs, research/query_service/ir/runtime/src/process/operator/map/edge_expand_intersection.rs, research/query_service/ir/runtime/src/process/operator/map/expand_intersect.rs, research/query_service/ir/runtime/src/process/operator/map/get_v.rs, research/query_service/ir/runtime/src/process/operator/map/mod.rs, research/query_service/ir/runtime/src/process/operator/map/path_end.rs, research/query_service/ir/runtime/src/process/operator/map/path_start.rs, research/query_service/ir/runtime/src/process/operator/mod.rs, research/query_service/ir/runtime/src/process/operator/subtask/apply.rs, research/query_service/ir/runtime/src/process/record.rs
1. Support EdgeExpandWithIntersection Op, for expanding edges with intersection
2. Support Unfold Op, to unfold collection entries.
3. Add CI for EdgeExpandWithIntersection cases.
Fixes
=> [IR Runtime] Support EdgeExpandWithIntersection and Unfold Op in Runtime

research/query_service/ir/common/src/lib.rs, research/query_service/ir/core/src/plan/logical.rs, research/query_service/ir/core/src/plan/physical.rs, research/query_service/ir/proto/algebra.proto
Reverts longbinlai/GraphScope#135
=> Revert "[IR Core] Support Union of Intersection in IR-Core"

research/query_service/ir/integrated/tests/expand_test.rs, research/query_service/ir/runtime/src/process/operator/map/expand_intersect.rs
=> [IR Runtime] Support expand vertices with edge filters on ExpandIntersect

research/query_service/ir/runtime/src/process/operator/flatmap/unfold.rs
=> [IR Runtime] fix ci test in unfold
